#!/bin/bash

# If a program does not exit with zero status, exit
checkExitStatus() {
    if [ $? -ne 0 ]; then
        exit $?
    fi
}


if [ $# -ne 2 ]; then
    echo "Two parameters are expected."
    echo "Example: ./runclient chipmunk.cs.umanitoba.ca 15000"
    exit 1
else
    echo "Compiling files..."
    make
    checkExitStatus

    echo
    echo "Creating RMI stubs..."
    make rmic
    checkExitStatus

    echo
    echo "Starting Client.."
    java DaytimeClient2 $1 $2

    exit 0
fi
