#!/bin/bash

# If a program does not exit with zero status, exit
checkExitStatus() {
    if [ $? -ne 0 ]; then
        exit $?
    fi
}


if [ $# -ne 1 ]; then
    echo "One parameter is expected."
    echo "Example: ./runserver 15000"
    exit 1
else
    echo "Compiling files..."
    make
    checkExitStatus

    echo
    echo "Creating RMI stubs..."
    make rmic
    checkExitStatus

    echo
    echo "Starting Server..."
    java DaytimeServer2 $1

    exit 0
fi
